# Autogenerated wrapper script for cilantro_jll for x86_64-w64-mingw32-cxx11
export libcilantro

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("cilantro")
JLLWrappers.@declare_library_product(libcilantro, "libcilantro.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libcilantro,
        "bin\\libcilantro.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
